### ISSUE TITLE
`Matrix.concatVertical` mutates the first argument

### ISSUE THREAD

**Issue by Enkidatron** [eeue56/elm-flat-matrix#16]
Please see https://ellie-app.com/8R8VgZZnMa1/0 for a demo of this behavior. 

It appears that using `Matrix.concatVertical` results in the first argument being mutated. Specifically, the `data` array in the first argument will have the `data` array from the second argument added to the end of it. The `size` value is not changed, so the resulting record is an invalid record (the data is larger than the size value would indicate). 

Of course, even if the `size` value was updated to match, the mutation should not happen in the first place.

**Comment by TSFoster** [comment]
Wow, this seems like a really serious issue with core's `Array`! I'm afraid I don't keep up-to-date with elm's development process, is it a known issue @eeue56?

FWIW, I can replicate the bug on my machine, and I've made a SSCCE independent of elm-flat-matrix: <https://ellie-app.com/5fcL2d7TYa1/0>. Also, this bug *doesn't* appear to be present in `Array.Hamt`.

**Comment by TSFoster** [comment]
Also: if you keep clicking the next button in @Enkidatron's [example](https://ellie-app.com/8R8VgZZnMa1/0), it does eventually start working as expected, after the 8th click.

**Comment by eeue56** [comment]
should be fixed in master
